places = ["Bali", "Thailand", "Dubai", "Japan", "Huwaii"]
print(places)
print(sorted(places))
print(places)
print(sorted(places, reverse = True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse = True)
print(f"There are {len(places)} places I would like to travel to:\t\nThey are:\t\n{places[0].title()}; {places[1].title()}, {places[2].title()}, {places[3].title()}")
